config/routes.rb
Rails.application.routes.draw do

    get "/" => "users#home"
    get "/home" => "users#home"

    devise_for :users, :controllers => {:registrations => "registrations"}
    resources :users do
        resources :messages
    end
    resources :photos
    resources :languages
    resources :neighborhoods
    resources :hobbies

    get "/search_local_places" => "users#search_local_places"
    get "/show_local_places" => "users#show_local_places"
    get "/get_places_data" => "users#get_places_data"
    get "/local_places_json" => "users#local_places_json"

    get "/filter_messages" => "messages#filter_messages"
    get "/my_messages/:id" => "messages#my_messages"

end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :set_message, only: [:show, :edit, :update, :destroy]

    # ======= filter_messages =======
    def filter_messages
        puts "\n******* filter_messages *******"
        # @users = User.all
        @users = User.where.not(:id => current_user[:id] )
        @messages = Message.where(:receiver_id => params[:receiver_id], :user_id => current_user[:id] )
        @message = @messages.first
        puts "@messages: #{@messages}"
        respond_to do |format|
            format.html { render :index }
        end
    end

    # ======= my_messages =======
    def my_messages
        puts "\n******* my_messages *******"
        @users = User.where.not(:id => current_user[:id] )
        @messages = current_user.messages
        puts "@messages: #{@messages}"
        respond_to do |format|
            format.html { render :index }
        end
    end

    # ======= new =======
    def new
        puts "\n******* new *******"
        @users = User.where.not(:id => current_user[:id] )
        @message = Message.new
    end

    # ======= create =======
    def create
        puts "\n******* create *******"
        @message = Message.new(message_params)
        @users = User.all
        @messages = current_user.messages
        puts "@messages: #{@messages}"

        respond_to do |format|
            if @message.save
                format.html { redirect_to user_message_path(current_user[:id], @message[:id]), notice: 'Message was successfully created.' }
            else
                format.html { render :my_messages }
            end
        end
    end

    # ======= index =======
    def index
        puts "\n******* index *******"
        @messages = Message.all
        # @users = User.all
        @users = User.where.not(:id => current_user[:id] )
    end

    # ======= edit =======
    def edit
        puts "\n******* edit *******"
        @users = User.where.not(:id => current_user[:id] )
    end

    # ======= update =======
    def update
        puts "\n******* update *******"
        @users = User.all
        respond_to do |format|
            if @message.update(message_params)
                format.html { redirect_to user_messages_path(current_user), notice: 'Message was successfully updated.' }
            else
                format.html { render :edit }
            end
        end
    end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # ======= destroy =======
    def destroy
        puts "\n******* destroy *******"
        @message.destroy
            respond_to do |format|
            format.html { redirect_to user_messages(current_user), notice: 'Message was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
        # Use callbacks to share common setup or constraints between actions.
        def set_message
            @message = Message.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def message_params
            params.require(:message).permit(:user_id, :receiver_id, :content)
        end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |f| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>
      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <!-- ======= select box source arrays ======= -->
    <% selected_user = nil %>
    <% if message[:user_id] %>
        <% selected_user = @message[:user_id] %>
    <% end %>

    <% user_name_ids = [] %>
    <% @users.each_with_index do |user, index| %>
        <% user_name_ids << [user[:fullname], user[:id]] %>
    <% end %>

    <div class="actions">
        <%= f.select(:receiver_id, options_for_select(user_name_ids, selected_user)) %>
        <%= f.hidden_field :user_id, id: "user_id", value:current_user[:id].to_s %>
        <%= f.text_area :content, id: "content", id: "messageBox" %>
        <%= f.submit %>
    </div>
<% end %>

app/views/messages/edit.html.erb
<h2>Edit a Message</h2>

<%= form_with(model: @message, url: user_message_path(current_user[:id], @message), local: true) do |f| %>
    <% if @message.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>
        <ul>
            <% @message.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>

    <div class="actions">
      <%= f.hidden_field :receiver_id, id: "receiver_id", value: @message[:receiver_id].to_s %>
      <%= f.hidden_field :user_id, id: "user_id", value: current_user[:id].to_s %>
      <%= f.text_field :content, id: "content" %>
      <%= f.submit %>
    </div>
<% end %>

<div class="links">
  <%= link_to 'Show', user_message_path(current_user, @message), class: "linkButton" %> |
  <%= link_to 'Back', user_messages_path(current_user), class: "linkButton" %>
</div>

app/views/messages/index.html.erb
<h2>Your Messages</h2>
<!-- ======= select box source arrays ======= -->
<div class="wrapper">
  <div id="filterMessages">
    <% user_name_ids = [] %>
    <% user_name_ids << "View Conversations With.." %>
    <% @users.each_with_index do |user, index| %>
        <% user_name_ids << [user[:fullname], user[:id]] %>
    <% end %>
    <%= form_with(model: @message, url: "/filter_messages", method: "get", local: true) do |f| %>
        <div class="actions">
            <%= f.select(:receiver_id, options_for_select(user_name_ids)) %>
            <%= f.hidden_field :user_id, id: "user_id", value:current_user[:id].to_s %>
            <%= f.submit "Filter", id: "filterButton" %>
        </div>
    <% end %>
  </div>
  <div id="newMessages">
    <%= link_to 'New Message', new_user_message_path(current_user[:id]), class: "linkButton" %>
  </div>
</div>
<br>
<table id="messageTable">
  <thead>
    <tr>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% @messages.each do |message| %>
        <% receiver = User.find(message[:receiver_id]) %>
        <% receiver_id = receiver[:id] %>
        <% receiver_name = receiver[:fullname] %>
        <tr>
          <td class="messageWith"> &#187; <% receiver_id.to_s %> <%= link_to receiver_name, user_message_path(current_user, message), class: "linkButton" %></td>
          <td class="messageTime">Sent at: <%= message[:created_at] %></td>
          <td class="messageAction"><%= link_to 'Edit', edit_user_message_path(current_user, message), class: "linkButton" %></td>
          <td class="messageAction"><%= link_to 'Delete', user_message_path(current_user, message), method: :delete, data: { confirm: 'Are you sure?' }, class: "linkButton" %></td>
        </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/messages/new.html.erb
<h2>DsCene: Create a New Message</h2>
<%= form_with(model: @message, url: user_messages_path(current_user[:id]), local: true) do |f| %>
    <% if @message.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>
        <ul>
            <% @message.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>

    <!-- ======= select box source arrays ======= -->
    <% selected_user = nil %>
    <% if @message[:user_id] %>
      <% selected_user = @message[:user_id] %>
    <% end %>

    <% user_name_ids = [] %>
    <% user_name_ids << "Select a DsCene Member" %>
    <% @users.each_with_index do |user, index| %>
      <% user_name_ids << [user[:fullname], user[:id]] %>
    <% end %>
    <div class="formBox">
      <div class="actions">
        <%= f.label :receiver_id, "Send a Message to:" %>
        <%= f.select(:receiver_id, options_for_select(user_name_ids, selected_user)) %>
        <%= f.hidden_field :user_id, id: "user_id", value:current_user[:id].to_s %> <br> <br>
        <%= f.text_area :content, id: "content", id: "messageBox" %> <br>
        <%= f.submit "Send", class: "homeButtons" %>
      </div>
    </div>
<% end %>
<br>
<div class="otherLinks">
  <%= link_to 'Back', user_messages_path(current_user), class: "linkButton" %>
</div>

app/views/messages/show.html.erb
<h2>Create a New Message</h2>

<p><%= @message[:content] %></p>

<div class="links">
  <%= link_to 'Edit', edit_user_message_path(current_user, @message) %> |
  <%= link_to 'Back', user_messages_path %>
</div>