config/routes.rb
Rails.application.routes.draw do

    get "/" => "users#home"
    get "/home" => "users#home"

    devise_for :users, :controllers => {:registrations => "registrations"}
    resources :users do
        resources :messages
    end
    resources :photos
    resources :languages
    resources :neighborhoods
    resources :hobbies

    get "/search_local_places" => "users#search_local_places"
    get "/show_local_places" => "users#show_local_places"
    get "/get_places_data" => "users#get_places_data"
    get "/local_places_json" => "users#local_places_json"

    get "/filter_messages" => "messages#filter_messages"
    get "/my_messages/:id" => "messages#my_messages"

end

app/models/hobby.rb
class Hobby < ApplicationRecord
  belongs_to :user
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :set_hobby, only: [:show, :edit, :update, :destroy]

  # GET /hobbies
  # GET /hobbies.json
  def index
    @hobbies = Hobby.all
  end

  # GET /hobbies/1
  def show
  end

  # GET /hobbies/new
  def new
    @hobby = Hobby.new
  end

  # GET /hobbies/1/edit
  def edit
  end

  # POST /hobbies
  # POST /hobbies.json
  def create
    @hobby = Hobby.new(hobby_params)

    respond_to do |format|
      if @hobby.save
        format.html { redirect_to user_path(current_user[:id]), notice: 'Hobby was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /hobbies/1
  # PATCH/PUT /hobbies/1.json
  def update
    respond_to do |format|
      if @hobby.update(hobby_params)
        format.html { redirect_to user_path(current_user[:id]), notice: 'Hobby was successfully updated.' }
        format.json { render :show, status: :ok, location: @hobby }
      else
        format.html { render :edit }
        format.json { render json: @hobby.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hobbies/1
  # DELETE /hobbies/1.json
  def destroy
    @hobby.destroy
    respond_to do |format|
      format.html { redirect_to hobbies_url, notice: 'Hobby was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hobby
      @hobby = Hobby.find(params[:id])
      puts "@hobby: #{@hobby.inspect}"

    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def hobby_params
      params.require(:hobby).permit(:user_id, :reading, :gym, :movie, :dancing, :outside, :food, :drinks, :museums)
    end
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/views/hobbies/_form.html.erb
<%= form_with(model: hobby, local: true) do |form| %>
  <% if hobby.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hobby.errors.count, "error") %> prohibited this hobby from being saved:</h2>

      <ul>
      <% hobby.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="actions">
    <%= form.label :reading, "Whats your favorite book?" %> <br>
    <%= form.text_field :reading, autofocus: true,  class: "typeBox" %><br>
    <%= form.label :gym, "Whats your favorite sport?" %> <br>
    <%= form.text_field :gym, autofocus: true,  class: "typeBox" %><br>
    <%= form.label :movie, "What kind of movies do you like?" %> <br>
    <%= form.text_field :movie, autofocus: true,  class: "typeBox" %><br>
    <%= form.label :dancing, "What kind of music do you like?" %> <br>
    <%= form.text_field :dancing, autofocus: true,  class: "typeBox" %><br>
    <%= form.label :outside, "What type of outdoor activities do you enjoy?" %> <br>
    <%= form.text_field :outside, autofocus: true,  class: "typeBox" %><br>
    <%= form.label :food, "What's your favorite food?" %> <br>
    <%= form.text_field :food, autofocus: true,  class: "typeBox" %><br>
    <%= form.label :drinks, "What's your prefered drink?" %> <br>
    <%= form.text_field :drinks, autofocus: true,  class: "typeBox" %><br>
    <%= form.label :museums, "Whats your favorite museum in DC?" %> <br>
    <%= form.text_field :museums, autofocus: true,  class: "typeBox" %><br>
    <%= form.hidden_field :user_id, value: current_user[:id] %>
    <%= form.submit %>
</div>
  <% end %>

app/views/hobbies/edit.html.erb
<h2>Update your Interests &amp; Hobbies</h2>

<%= render 'form', hobby: @hobby %>
<div class="links">
  <%= link_to 'Show', @hobby %> |
  <%= link_to 'Back', hobbies_path %>
</div>

app/views/hobbies/index.html.erb
<h2>Hobbies</h2>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hobbies.each do |hobby| %>
      <tr>
        <td><%= link_to 'Show', hobby %></td>
        <td><%= link_to 'Edit', edit_hobby_path(hobby) %></td>
        <td><%= link_to 'Destroy', hobby, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="links">
  <%= link_to 'New Hobby', new_hobby_path %>
</div>

app/views/hobbies/new.html.erb
<h2>Interests &amp; Hobbies</h2>
<div id="hobbyform">
  <%= render 'form', hobby: @hobby %>
  <br>
  <div class="links">
    <%= link_to 'Back', hobbies_path, class: "linkButton" %>
  </div>
</div>

app/views/hobbies/show.html.erb
<h2>my hobbies:</h2><br>
<p>Favorite Book:    <%= @hobby[:reading] %></p>
<p>Favorite sport:   <%= @hobby[:gym] %></p>
<p>Favorite movie:   <%= @hobby[:movie] %></p>
<p>Favorite music genre:   <%= @hobby[:dancing] %></p>
<p>Favorite outdoor activity:    <%= @hobby[:outside] %></p>
<p>Favorite food:    <%= @hobby[:food] %></p>
<p>Favorite drink:   <%= @hobby[:drinks] %></p>
<p>Favorite museum in DC:    <%= @hobby[:museums] %></p>

<div class="links">
  <%= link_to 'Edit', edit_hobby_path(@hobby) %> |
  <%= link_to 'Back', hobbies_path %>
</div>