config/routes.rb
Rails.application.routes.draw do

    get "/" => "users#home"
    get "/home" => "users#home"

    devise_for :users, :controllers => {:registrations => "registrations"}
    resources :users do
        resources :messages
    end
    resources :photos
    resources :languages
    resources :neighborhoods
    resources :hobbies

    get "/search_local_places" => "users#search_local_places"
    get "/show_local_places" => "users#show_local_places"
    get "/get_places_data" => "users#get_places_data"
    get "/local_places_json" => "users#local_places_json"

    get "/filter_messages" => "messages#filter_messages"
    get "/my_messages/:id" => "messages#my_messages"

end

app/models/neighborhood.rb
class Neighborhood < ApplicationRecord
    validates :name, uniqueness: true
    validates :lat, presence: true
    validates :lng, presence: true
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  before_action :set_neighborhood, only: [:show, :edit, :update, :destroy]

  # GET /neighborhoods
  def index
    @neighborhoods = Neighborhood.all
  end

  # GET /neighborhoods/new
  def new
    @neighborhood = Neighborhood.new
  end

  # GET /neighborhoods/1/edit
  def edit
  end

  # POST /neighborhoods
  # POST /neighborhoods.json
  def create
    @neighborhood = Neighborhood.new(neighborhood_params)

    respond_to do |format|
      if @neighborhood.save
        format.html { redirect_to neighborhoods_path, notice: 'Neighborhood was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /neighborhoods/1
  # PATCH/PUT /neighborhoods/1.json
  def update
    respond_to do |format|
      if @neighborhood.update(neighborhood_params)
        format.html { redirect_to neighborhoods_path, notice: 'Neighborhood was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /neighborhoods/1
  # DELETE /neighborhoods/1.json
  def destroy
    @neighborhood.destroy
    respond_to do |format|
      format.html { redirect_to neighborhoods_url, notice: 'Neighborhood was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_neighborhood
      @neighborhood = Neighborhood.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def neighborhood_params
      params.require(:neighborhood).permit(:name, :lat, :lng)
    end
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

app/views/neighborhoods/_form.html.erb
<%= form_with(model: neighborhood, local: true) do |form| %>
  <% if neighborhood.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(neighborhood.errors.count, "error") %> prohibited this neighborhood from being saved:</h2>

      <ul>
      <% neighborhood.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div class="adminForms">
      <div class="field">
        <%= form.label :name, "Neighborhood Name: " %>
        <%= form.text_field :name, class: "typeBox" %> <br>
      </div>
      <div class="field">
        <%= form.label :lat, "Latitude: " %>
        <%= form.number_field :lat, step: :any, class: "typeBox" %> <br>
      </div>
      <div class="field">
        <%= form.label :lng, "Longitude: " %>
        <%= form.number_field :lng, step: :any, class: "typeBox" %> <br>
      </div>
      <%= form.submit %>
    </div>
  </div>
<% end %>
<br>

app/views/neighborhoods/edit.html.erb
<h2>Admin: Edit a Neighborhood</h2>
<div class="formBox">
  <%= render 'form', neighborhood: @neighborhood %>
</div>
<br>
<div class="otherLinks">
  <%= link_to 'Back', neighborhoods_path, class: "linkButton" %>
</div>

app/views/neighborhoods/index.html.erb
<h2>Admin: All Neighborhoods</h2>
<%= link_to "Add a New Neighborhood", new_neighborhood_path, class: "linkButton" %>
<br> <br>
<table>
  <thead>
    <tr>
      <th>Neighborhood</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @neighborhoods.each do |neighborhood| %>
      <tr>
        <td><%= neighborhood[:name] %></td>
        <td><%= neighborhood[:lat] %> &#176;</td>
        <td><%= neighborhood[:lng] %> &#176;</td>
        <td><%= link_to 'Edit', edit_neighborhood_path(neighborhood), class: "linkButton" %></td>
        <td><%= link_to 'Delete', neighborhood, method: :delete, data: { confirm: 'Are you sure?' }, class: "linkButton" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/neighborhoods/new.html.erb
<h2>Add Neighborhood to DCene Database</h2>
<div class="formBox">
  <%= render 'form', neighborhood: @neighborhood %>
</div>
<br>
<div class="otherLinks">
  <%= link_to 'Back', neighborhoods_path, class: "linkButton" %>
</div>